// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersistanceLayer.Context;

namespace PersistanceLayer.Migrations
{
    [DbContext(typeof(LogisticOperatorDbContext))]
    [Migration("20211028203821_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IAEW_LogisticOperator_Center_API.Models.DatosEnvio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactoComprador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEnvio")
                        .HasColumnType("int");

                    b.Property<long>("RepartidorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.ToTable("DatosEnvios");
                });

            modelBuilder.Entity("IAEW_LogisticOperator_Center_API.Models.Repartidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("IAEW_LogisticOperator_Center_API.Models.DatosEnvio", b =>
                {
                    b.HasOne("IAEW_LogisticOperator_Center_API.Models.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });
#pragma warning restore 612, 618
        }
    }
}
